# Generated by Django 2.1.7 on 2019-03-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('url', models.TextField()),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
