# Generated by Django 2.1.7 on 2019-03-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
