# Generated by Django 2.1.1 on 2019-04-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='likes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
