# Generated by Django 2.1.1 on 2019-04-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20190418_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='likes',
            new_name='num_likes',
        ),
    ]
