# Generated by Django 2.1.7 on 2019-03-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ave_rating', models.FloatField(default=0.0)),
                ('ave_wait', models.FloatField(default=0.0)),
                ('is_speciality', models.BooleanField()),
                ('is_veg', models.BooleanField()),
                ('price', models.FloatField()),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.Dish')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
    ]
