# Generated by Django 2.1.1 on 2019-04-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serves',
            name='dish_id',
        ),
        migrations.AddField(
            model_name='serves',
            name='dname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
