# Generated by Django 2.1.1 on 2019-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serves', '0002_auto_20190414_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='serves',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
