# Generated by Django 2.1.7 on 2019-04-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serves', '0002_auto_20190413_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='serves',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
