# Generated by Django 2.1.7 on 2019-03-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='like',
            field=models.CharField(default='', max_length=100),
        ),
    ]
